### ISSUE TITLE
Publish a non snapshot version of scoobi-kiji.

### ISSUE THREAD

**Issue by markhibberd** [NICTA/scoobi-kiji#4]
@etorreborre If possible could you publish a non-snapshot version of scoobi-kiji, even if it is just an arbitrary -M1 or similar. I am trying to get the builds to the point where they can work on the firewalled CI server which does not have access to oss.sonatype - so basically can't depend on any snapshots. 

Depends on #3

**Comment by etorreborre** [comment]
This is [done](https://oss.sonatype.org/content/repositories/releases/com/nicta/scoobi-kiji_2.10/0.1)
