### ISSUE TITLE
Removal of WibiData licence headers from some files

### ISSUE THREAD

**Issue by blever** [NICTA/scoobi-kiji#5]
The following files have both NICTA and WibiData copyright headers in them:
- `KijiKey.scala`
- `KijiRecordReader.scala`
- `KijiRow.scala`
- `KijiTableSplit.scala`

Were they just missed in a clean up or is this intentional? We should really have everything copyright NICTA ... at least for now.

**Comment by etorreborre** [comment]
It is intentional because the code was heavily copy-pasted from kiji-express.

**Comment by blever** [comment]
Righto. I guess that's ok ... not that I'm a lawyer :)
